# Generated by Django 4.0.4 on 2022-05-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tareasapp', '0002_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='priority_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tareasapp.priority'),
        ),
    ]
