# Generated by Django 4.0.4 on 2022-05-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tareasapp', '0005_alter_usuarios_options_alter_usuarios_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user_permissions',
        ),
    ]
